name: GraalVM Native Image builds
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    name: Generate Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build native Image
        run: |
          ./gradlew nativeCompile
      
      - name: Rename binary for OS
        shell: bash
        run: |
          cd build/native/nativeCompile
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv micronaut-mcp-tool-weather.exe micronaut-mcp-tool-weather-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv micronaut-mcp-tool-weather micronaut-mcp-tool-weather-macos
          else
            mv micronaut-mcp-tool-weather micronaut-mcp-tool-weather-linux
          fi
      
      - name: Attach binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/native/nativeCompile/micronaut-mcp-tool-weather-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
